return {
    prices = {
        ['Acorn']            = 2,
        ['Adaman Ore']       = 8500,
        ['Aht Urhgan Brass'] = 90,
        ['Almond']           = 38,
        ['Antlion Jaw']      = 2808,
        ['Aquamarine']       = 2509,
        ['Arrowwood Log']    = 5,
        ['Ash Log']          = 26,
        ['Bat Fang']         = 8,
        ['Beehive Chip']     = 333,
        ['Beetle Jaw']       = 133,
        ['Beetle Shell']     = 69,
        ['Black Pearl']      = 1203,
        ['Black Rock']       = 500,
        ['Blk. Tiger Fang']  = 440,
        ['Bloodwood Log']    = 8000,
        ['Blue Rock']        = 458,
        ['Bomb Arm']         = 165,
        ['Bomb Ash']         = 600,
        ['Bone Chip']        = 20,
        ['Buburimu Grape']   = 41,
        ['Cactus Stems']     = 531,
        ['Cattleya']         = 307,
        ['Chestnut']         = 33,
        ['Chestnut Log']     = 482,
        ['Chicken Bone']     = 11,
        ['Coffee Cherries']  = 84,
        ['Colibri Beak']     = 248,
        ['Copper Ore']       = 3,
        ['Coral Fragment']   = 1793,
        ['Coral Fungus']     = 166,
        ['Crab Shell']       = 392,
        ['Crawler Cocoon']   = 308,
        ['Crawler Egg']      = 36,
        ['Danceshroom']      = 656,
        ['Darksteel Ore']    = 3916,
        ['Date']             = 71,
        ['Demon Horn']       = 833,
        ['Diamond']          = 3895,
        ['Dogwood Log']      = 5,
        ['Dryad Root']       = 247,
        ["Dyer's Woad"]      = 186,
        ['Eastern Ginger']   = 39,
        ['Ebony Log']        = 2250,
        ['Eggplant']         = 12,
        ['Elm Log']          = 3583,
        ['Emerald']          = 3895,
        ['Faerie Apple']     = 12,
        ['Firesand']         = 328,
        ['Fish Scales']      = 26,
        ['Flax Flower']      = 55,
        ['Flint Stone']      = 5,
        ['Fresh Marjoram']   = 1,
        ['Fresh Mugwort']    = 1583,
        ['Fruit Seeds']      = 88,
        ['Giant Femur']      = 208,
        ['Gold Ingot']       = 2152,
        ['Gold Ore']         = 1333,
        ['Grain Seeds']      = 666,
        ['Green Rock']       = 416,
        ['H.Q. Crab Shell']  = 3408,
        ['H.Q. Pugil Scls.'] = 266,
        ['H.Q. Scp. Shell']  = 3505,
        ['Hatchet']          = 450,
        ['Helmet Mole']      = 731,
        ['Herb Seeds']       = 77,
        ['Holly Log']        = 157,
        ['Honey']            = 250,
        ['Igneous Rock']     = 178,
        ['Im. Tea Leaves']   = 5000,
        ['Iron Ore']         = 583,
        ['Iron Sand']        = 86,
        ['Khroma Ore']       = 350000,
        ['King Locust']      = 210,
        ['King Truffle']     = 3333,
        ['Kitron']           = 358,
        ['Lapis Lazuli']     = 1000,
        ['Lauan Log']        = 9,
        ['Lqr. Tree Sap']    = 1633,
        ['Lugworm']          = 1,
        ['Luminium Ore']     = 160000,
        ['Mahogany Log']     = 5750,
        ['Malboro Fiber']    = 7000,
        ['Maple Log']        = 16,
        ['Marid Tusk']       = 760,
        ['Merrow Scale']     = 256,
        ['Mistletoe']        = 1000,
        ['Mohbwa Grass']     = 750,
        ['Moko Grass']       = 5,
        ['Mushrm. Locust']   = 314,
        ['Mythril Ore']      = 750,
        ['Oak Log']          = 1333,
        ['Orichalcum Ore']   = 11666,
        ['Orpiment']         = 219,
        ['Oxblood']          = 13581,
        ['Painite']          = 3000,
        ['Pearl']            = 1230,
        ['Pebble']           = 1,
        ['Peph. Hive Chip']  = 750,
        ['Peridot']          = 1230,
        ['Persikos']         = 486,
        ['Petrified Log']    = 2833,
        ['Phalaenopsis']     = 782,
        ['Phil. Stone']      = 12000,
        ['Phoenix Feather']  = 1599,
        ['Pickaxe']          = 180,
        ["Pigeon's Blood"]   = 40000,
        ['Pine Nuts']        = 3,
        ['Platinum Ore']     = 5250,
        ['Puffball']         = 309,
        ['Purple Rock']      = 583,
        ['Rattan Lumber']    = 44,
        ['Red Moko Grass']   = 183,
        ['Red Rock']         = 1250,
        ['Reishi Mushroom']  = 1281,
        ['Revival Root']     = 57,
        ['Rock Salt']        = 4,
        ['Rosewood Log']     = 1400,
        ['Saruta Cotton']    = 16,
        ['Scorpion Claw']    = 279,
        ['Scorpion Shell']   = 708,
        ['Scream Fungus']    = 208,
        ['Seashell']         = 33,
        ['Shall Shell']      = 307,
        ['Shell Bug']        = 516,
        ['Sickle']           = 400,
        ['Silica']           = 833,
        ['Silver Ore']       = 225,
        ['Simsim']           = 84,
        ["Siren's Hair"]     = 180000,
        ['Skull Locust']     = 106,
        ['Sleepshroom']      = 27,
        ['Snapping Mole']    = 45,
        ['Soulflayer Robe']  = 10000,
        ['Spider Web']       = 1416,
        ['Spinel']           = 17000,
        ['Sulfur']           = 49,
        ['Tin Ore']          = 11,
        ['Toad Oil']         = 2333,
        ['Topaz']            = 25000,
        ['Translucent Rock'] = 205,
        ['Tree Cuttings']    = 583,
        ['Turquoise']        = 2000,
        ['Turtle Shell']     = 1254,
        ['Vegetable Seeds']  = 77,
        ['Walnut Log']       = 134,
        ['White Rock']       = 205,
        ['Wijnruit']         = 33,
        ['Wild Onion']       = 1000,
        ['Willow Log']       = 44,
        ['Win. Tea Leaves']  = 4,
        ['Wivre Horn']       = 760,
        ['Wivre Maul']       = 3700,
        ['Woozyshroom']      = 247,
        ['Wyvern Scales']    = 3250,
        ['Yagudo Cherry']    = 12,
        ['Yellow Rock']      = 833,
        ['Yew Log']          = 97,
        ['Zinc Ore']         = 27,
    },
    auction = {
        'Adaman Ore',
        'Beehive Chip',
        'Black Rock',
        'Bloodwood Log',
        'Blue Rock',
        'Bomb Ash',
        'Crawler Cocoon',
        'Darksteel Ore',
        'Demon Horn',
        'Dogwood Log',
        'Ebony Log',
        'Elm Log',
        'Fresh Mugwort',
        'Gold Ore',
        'Grain Seeds',
        'Green Rock',
        'Honey',
        'Im. Tea Leaves',
        'Iron Ore',
        'Khroma Ore',
        'King Truffle',
        'Lapis Lazuli',
        'Lqr. Tree Sap',
        'Luminium Ore',
        'Mahogany Log',
        'Malboro Fiber',
        'Mohbwa Grass',
        'Mythril Ore',
        'Oak Log',
        'Orichalcum Ore',
        'Painite',
        'Peph. Hive Chip',
        'Petrified Log',
        'Phil. Stone',
        "Pigeon's Blood",
        'Platinum Ore',
        'Purple Rock',
        'Red Moko Grass',
        'Red Rock',
        'Rosewood Log',
        'Scorpion Shell',
        'Shell Bug',
        'Silica',
        'Silver Ore',
        "Siren's Hair",
        'Soulflayer Robe',
        'Spider Web',
        'Spinel',
        'Toad Oil',
        'Topaz',
        'Tree Cuttings',
        'Turquoise',
        'Wild Onion',
        'Wivre Maul',
        'Wyvern Scales',
        'Yellow Rock',
    },
};
